version: '3.3'

services:
  lalib:
    build: 
      context: .
    volumes: 
      - type: bind
        source: './'
        target: '/home/mathlib'
    command: >
      bash -c "cd /home/mathlib && 
      cmake -B ../build_gcc10 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 &&
      cmake -B ../build_gcc10_blas -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 &&
      cmake -B ../build_gcc10_lapack -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 &&
      cmake -B ../build_gcc10_gpu -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER=g++-10 &&
      bash"
    tty: true
    stdin_open: true
